name: pipeline

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --no-audit --no-fund --no-optional
    - name: Lint
      run: npm run eslint
    - name: Build
      run: npm run build
