name: pipeline

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run eslint
